version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 112547104148.dkr.ecr.us-east-1.amazonaws.com
      - echo "Pre-build phase complete."
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t lamptey-flask .
      - docker tag lamptey-flask:latest 112547104148.dkr.ecr.us-east-1.amazonaws.com/lamptey-flask:latest
      - echo "Build phase complete."
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 112547104148.dkr.ecr.us-east-1.amazonaws.com/lamptey-flask:latest
      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"lamptey-flaskapp-container","imageUri":"%s"}]' 112547104148.dkr.ecr.us-east-1.amazonaws.com/lamptey-flask:latest > imagedefinitions.json
      - echo "Post-build phase complete."

artifacts:
  files:
    - imagedefinitions.json
    - app.py
    - Dockerfile
    - requirements.txt
